/* AUTO-GENERATED by scripts/gen_formulas.js — 勿手改 */
export default {
  "A∪B={x|x∈A或x∈B}": {
    "l": "A \\cup B = \\{x \\mid x \\in A \\text{ 或 } x \\in B\\}",
    "img": "/common/formulas/math/46c4c6a9af0a.png",
    "subj": "数学"
  },
  "A∩B={x|x∈A且x∈B}": {
    "l": "A \\cap B = \\{x \\mid x \\in A \\text{ 且 } x \\in B\\}",
    "img": "/common/formulas/math/46c4c6a9af0a.png",
    "subj": "数学"
  },
  "|A∪B|=|A|+|B|-|A∩B|": {
    "l": "|A \\cup B| = |A| + |B| - |A \\cap B|",
    "img": "/common/formulas/math/46c4c6a9af0a.png",
    "subj": "数学"
  },
  "f(-x)=-f(x)": {
    "l": "f(-x) = -f(x)",
    "img": "/common/formulas/math/8a76e3c75906.png",
    "subj": "数学"
  },
  "f(-x)=f(x)": {
    "l": "f(-x) = f(x)",
    "img": "/common/formulas/math/8a76e3c75906.png",
    "subj": "数学"
  },
  "f(x+T)=f(x)": {
    "l": "f(x+T) = f(x)",
    "img": "/common/formulas/math/8a76e3c75906.png",
    "subj": "数学"
  },
  "y=f(x+a)": {
    "l": "y = f(x+a)",
    "img": "/common/formulas/math/8a76e3c75906.png",
    "subj": "数学"
  },
  "a^m·a^n=a^(m+n)": {
    "l": "a^m \\cdot a^n = a^{m+n}",
    "img": "/common/formulas/math/fe17ec2e45a2.png",
    "subj": "数学"
  },
  "log_a(MN)=log_a M+log_a N": {
    "l": "\\log_a (MN) = \\log_a M + \\log_a N",
    "img": "/common/formulas/math/fe17ec2e45a2.png",
    "subj": "数学"
  },
  "log_a a^x=x": {
    "l": "\\log_a a^x = x",
    "img": "/common/formulas/math/fe17ec2e45a2.png",
    "subj": "数学"
  },
  "a^(log_a N)=N": {
    "l": "a^{\\log_a N} = N",
    "img": "/common/formulas/math/fe17ec2e45a2.png",
    "subj": "数学"
  },
  "x=-b/(2a)": {
    "l": "x = -\\frac{b}{2a}",
    "img": "/common/formulas/math/00c2b1a50254.png",
    "subj": "数学"
  },
  "Δ=b²-4ac": {
    "l": "\\Delta = b^2 - 4ac",
    "img": "/common/formulas/math/00c2b1a50254.png",
    "subj": "数学"
  },
  "x1+x2=-b/a": {
    "l": "x_1 + x_2 = -\\frac{b}{a}",
    "img": "/common/formulas/math/00c2b1a50254.png",
    "subj": "数学"
  },
  "x1·x2=c/a": {
    "l": "x_1 \\cdot x_2 = \\frac{c}{a}",
    "img": "/common/formulas/math/00c2b1a50254.png",
    "subj": "数学"
  },
  "(x^n)'=nx^(n-1)": {
    "l": "(x^n)' = n x^{n-1}",
    "img": "/common/formulas/math/86d29542d3f1.png",
    "subj": "数学"
  },
  "(sin x)'=cos x": {
    "l": "(sin x)' = cos x",
    "img": "/common/formulas/math/86d29542d3f1.png",
    "subj": "数学"
  },
  "(cos x)'=-sin x": {
    "l": "(cos x)' = -sin x",
    "img": "/common/formulas/math/86d29542d3f1.png",
    "subj": "数学"
  },
  "(e^x)'=e^x": {
    "l": "(e^x)' = e^x",
    "img": "/common/formulas/math/86d29542d3f1.png",
    "subj": "数学"
  },
  "(ln x)'=1/x": {
    "l": "(\\ln x)' = \\frac{1}{x}",
    "img": "/common/formulas/math/86d29542d3f1.png",
    "subj": "数学"
  },
  "(uv)'=u'v+uv'": {
    "l": "(uv)' = u'v + uv'",
    "img": "/common/formulas/math/86d29542d3f1.png",
    "subj": "数学"
  },
  "sin²+cos²=1": {
    "l": "\\sin^2 x + \\cos^2 x = 1",
    "img": "/common/formulas/math/9bed8994d2d1.png",
    "subj": "数学"
  },
  "sin(A±B)=sinAcosB±cosAsinB": {
    "l": "\\sin(A \\pm B) = \\sin A \\cos B \\pm \\cos A \\sin B",
    "img": "/common/formulas/math/9bed8994d2d1.png",
    "subj": "数学"
  },
  "cos2α=2cos²α-1": {
    "l": "\\cos 2\\alpha = 2\\cos^2 \\alpha - 1",
    "img": "/common/formulas/math/9bed8994d2d1.png",
    "subj": "数学"
  },
  "sin2α=2sinαcosα": {
    "l": "\\sin 2\\alpha = 2 \\sin \\alpha \\cos \\alpha",
    "img": "/common/formulas/math/9bed8994d2d1.png",
    "subj": "数学"
  },
  "y=Asin(ωx+φ)": {
    "l": "y = A \\sin(\\omega x + \\varphi)",
    "img": "/common/formulas/math/9bed8994d2d1.png",
    "subj": "数学"
  },
  "T=2π/ω": {
    "l": "T = \\frac{2\\pi}{\\omega}",
    "img": "/common/formulas/physics/614f37e89ce2.png",
    "subj": "物理"
  },
  "a·b=|a||b|cosθ": {
    "l": "\\vec{a} \\cdot \\vec{b} = |\\vec{a}||\\vec{b}|\\cos\\theta",
    "img": "/common/formulas/math/3e6575ab871d.png",
    "subj": "数学"
  },
  "a·b=x1x2+y1y2": {
    "l": "\\vec{a} \\cdot \\vec{b} = x_1 x_2 + y_1 y_2",
    "img": "/common/formulas/math/3e6575ab871d.png",
    "subj": "数学"
  },
  "|a|=√(x²+y²)": {
    "l": "|\\vec{a}| = \\sqrt{x^2 + y^2}",
    "img": "/common/formulas/math/3e6575ab871d.png",
    "subj": "数学"
  },
  "a∥b⇒x1y2=x2y1": {
    "l": "\\vec{a} \\parallel \\vec{b} \\Rightarrow x_1 y_2 = x_2 y_1",
    "img": "/common/formulas/math/3e6575ab871d.png",
    "subj": "数学"
  },
  "an=a1+(n-1)d": {
    "l": "a_n = a_1 + (n-1)d",
    "img": "/common/formulas/math/ac42e132669e.png",
    "subj": "数学"
  },
  "Sn=n(a1+an)/2": {
    "l": "S_n = \\frac{n(a_1 + a_n)}{2}",
    "img": "/common/formulas/math/ac42e132669e.png",
    "subj": "数学"
  },
  "an=a1·q^(n-1)": {
    "l": "a_n = a_1 \\cdot q^{n-1}",
    "img": "/common/formulas/math/ac42e132669e.png",
    "subj": "数学"
  },
  "Sn=a1(1-q^n)/(1-q)": {
    "l": "S_n = \\frac{a_1(1 - q^n)}{1 - q}",
    "img": "/common/formulas/math/ac42e132669e.png",
    "subj": "数学"
  },
  "a+b≥2√(ab)": {
    "l": "a + b \\ge 2\\sqrt{ab}",
    "img": "/common/formulas/math/612cb1f5260a.png",
    "subj": "数学"
  },
  "(a+b+c)/3≥³√(abc)": {
    "l": "\\frac{a+b+c}{3} \\ge \\sqrt[3]{abc}",
    "img": "/common/formulas/math/612cb1f5260a.png",
    "subj": "数学"
  },
  "(Σa_i²)(Σb_i²)≥(Σa_ib_i)²": {
    "l": "(\\sum a_i^2)(\\sum b_i^2) \\ge (\\sum a_i b_i)^2",
    "img": "/common/formulas/math/612cb1f5260a.png",
    "subj": "数学"
  },
  "d=|n·PA|/|n|": {
    "l": "d = \\frac{|\\vec{n} \\cdot \\vec{PA}|}{|\\vec{n}|}",
    "img": "/common/formulas/math/44ebeb3acafb.png",
    "subj": "数学"
  },
  "V=1/3·Sh": {
    "l": "V = \\frac{1}{3} S h",
    "img": "/common/formulas/math/44ebeb3acafb.png",
    "subj": "数学"
  },
  "cosθ=|n1·n2|/(|n1||n2|)": {
    "l": "\\cos\\theta = \\frac{|\\vec{n_1} \\cdot \\vec{n_2}|}{|\\vec{n_1}||\\vec{n_2}|}",
    "img": "/common/formulas/math/44ebeb3acafb.png",
    "subj": "数学"
  },
  "d=|Ax0+By0+C|/√(A²+B²)": {
    "l": "d = \\frac{|Ax_0 + By_0 + C|}{\\sqrt{A^2 + B^2}}",
    "img": "/common/formulas/math/c592910d413a.png",
    "subj": "数学"
  },
  "x²/a²+y²/b²=1": {
    "l": "\\frac{x^2}{a^2} + \\frac{y^2}{b^2} = 1",
    "img": "/common/formulas/math/c592910d413a.png",
    "subj": "数学"
  },
  "x²/a²-y²/b²=1": {
    "l": "\\frac{x^2}{a^2} - \\frac{y^2}{b^2} = 1",
    "img": "/common/formulas/math/c592910d413a.png",
    "subj": "数学"
  },
  "y²=2px": {
    "l": "y^2 = 2px",
    "img": "/common/formulas/math/c592910d413a.png",
    "subj": "数学"
  },
  "c²=a²-b²(椭圆)": {
    "l": "c^2 = a^2 - b^2 \\quad \\text{(椭圆)}",
    "img": "/common/formulas/math/c592910d413a.png",
    "subj": "数学"
  },
  "c²=a²+b²(双曲线)": {
    "l": "c^2 = a^2 + b^2 \\quad \\text{(双曲线)}",
    "img": "/common/formulas/math/c592910d413a.png",
    "subj": "数学"
  },
  "A_n^k=n!/(n-k)!": {
    "l": "A_n^k = \\frac{n!}{(n-k)!}",
    "img": "/common/formulas/math/0df42dc3e201.png",
    "subj": "数学"
  },
  "C_n^k=n!/[k!(n-k)!]": {
    "l": "C_n^k = \\frac{n!}{k!(n-k)!}",
    "img": "/common/formulas/math/0df42dc3e201.png",
    "subj": "数学"
  },
  "P(X=k)=C_n^k·p^k·(1-p)^(n-k)": {
    "l": "P(X=k) = C_n^k \\cdot p^k \\cdot (1-p)^{n-k}",
    "img": "/common/formulas/math/0df42dc3e201.png",
    "subj": "数学"
  },
  "E(X)=np": {
    "l": "E(X) = np",
    "img": "/common/formulas/math/0df42dc3e201.png",
    "subj": "数学"
  },
  "D(X)=np(1-p)": {
    "l": "D(X) = np(1-p)",
    "img": "/common/formulas/math/0df42dc3e201.png",
    "subj": "数学"
  },
  "v=v0+at": {
    "l": "v = v_0 + at",
    "img": "/common/formulas/physics/ed3b561128a8.png",
    "subj": "物理"
  },
  "x=v0t+½at²": {
    "l": "x = v_0 t + \\frac{1}{2} a t^2",
    "img": "/common/formulas/physics/ed3b561128a8.png",
    "subj": "物理"
  },
  "v²-v0²=2ax": {
    "l": "v^2 - v_0^2 = 2ax",
    "img": "/common/formulas/physics/ed3b561128a8.png",
    "subj": "物理"
  },
  "v̄=(v0+v)/2": {
    "l": "\\bar{v} = \\frac{v_0 + v}{2}",
    "img": "/common/formulas/physics/ed3b561128a8.png",
    "subj": "物理"
  },
  "h=½gt²": {
    "l": "h = \\frac{1}{2} g t^2",
    "img": "/common/formulas/physics/ed3b561128a8.png",
    "subj": "物理"
  },
  "H=v0²/(2g)": {
    "l": "H = \\frac{v_0^2}{2g}",
    "img": "/common/formulas/physics/ed3b561128a8.png",
    "subj": "物理"
  },
  "G=mg": {
    "l": "G = mg",
    "img": "/common/formulas/physics/1d514924e264.png",
    "subj": "物理"
  },
  "F=kx": {
    "l": "F = kx",
    "img": "/common/formulas/physics/1d514924e264.png",
    "subj": "物理"
  },
  "f=μN": {
    "l": "f = \\mu N",
    "img": "/common/formulas/physics/1d514924e264.png",
    "subj": "物理"
  },
  "F=√(Fx²+Fy²)": {
    "l": "F = \\sqrt{F_x^2 + F_y^2}",
    "img": "/common/formulas/physics/1d514924e264.png",
    "subj": "物理"
  },
  "F合=ma": {
    "l": "F_\\text{合} = ma",
    "img": "/common/formulas/physics/8398c3204a9b.png",
    "subj": "物理"
  },
  "N=mg+ma(超重)": {
    "l": "N = mg + ma \\quad \\text{(超重)}",
    "img": "/common/formulas/physics/8398c3204a9b.png",
    "subj": "物理"
  },
  "N=mg-ma(失重)": {
    "l": "N = mg - ma \\quad \\text{(失重)}",
    "img": "/common/formulas/physics/8398c3204a9b.png",
    "subj": "物理"
  },
  "x=v0t": {
    "l": "x = v_0 t",
    "img": "/common/formulas/physics/9acae4baba40.png",
    "subj": "物理"
  },
  "y=½gt²": {
    "l": "y = \\frac{1}{2} g t^2",
    "img": "/common/formulas/physics/9acae4baba40.png",
    "subj": "物理"
  },
  "F向=mv²/r": {
    "l": "F_\\text{向} = \\frac{m v^2}{r}",
    "img": "/common/formulas/physics/9acae4baba40.png",
    "subj": "物理"
  },
  "F=Gm1m2/r²": {
    "l": "F = \\frac{G m_1 m_2}{r^2}",
    "img": "/common/formulas/physics/9acae4baba40.png",
    "subj": "物理"
  },
  "v=√(GM/r)": {
    "l": "v = \\sqrt{\\frac{GM}{r}}",
    "img": "/common/formulas/physics/9acae4baba40.png",
    "subj": "物理"
  },
  "T=2π√(r³/GM)": {
    "l": "T = 2\\pi \\sqrt{\\frac{r^3}{GM}}",
    "img": "/common/formulas/physics/9acae4baba40.png",
    "subj": "物理"
  },
  "W=Fscosθ": {
    "l": "W = Fs \\cos\\theta",
    "img": "/common/formulas/physics/cba3fb462738.png",
    "subj": "物理"
  },
  "P=Fv": {
    "l": "P = Fv",
    "img": "/common/formulas/physics/cba3fb462738.png",
    "subj": "物理"
  },
  "Ek=½mv²": {
    "l": "E_k = \\frac{1}{2} m v^2",
    "img": "/common/formulas/physics/cba3fb462738.png",
    "subj": "物理"
  },
  "Ep=mgh": {
    "l": "E_p = mgh",
    "img": "/common/formulas/physics/cba3fb462738.png",
    "subj": "物理"
  },
  "Ep=½kx²": {
    "l": "E_p = \\frac{1}{2} k x^2",
    "img": "/common/formulas/physics/cba3fb462738.png",
    "subj": "物理"
  },
  "W合=ΔEk": {
    "l": "W_\\text{合} = \\Delta E_k",
    "img": "/common/formulas/physics/cba3fb462738.png",
    "subj": "物理"
  },
  "p=mv": {
    "l": "p = mv",
    "img": "/common/formulas/physics/947e8ed8a8c5.png",
    "subj": "物理"
  },
  "F·t=Δp": {
    "l": "F \\cdot t = \\Delta p",
    "img": "/common/formulas/physics/947e8ed8a8c5.png",
    "subj": "物理"
  },
  "m1v1+m2v2=m1v1'+m2v2'": {
    "l": "m_1 v_1 + m_2 v_2 = m_1 v_1' + m_2 v_2'",
    "img": "/common/formulas/physics/947e8ed8a8c5.png",
    "subj": "物理"
  },
  "v共=(m1v1+m2v2)/(m1+m2)": {
    "l": "v_\\text{共} = \\frac{m_1 v_1 + m_2 v_2}{m_1 + m_2}",
    "img": "/common/formulas/physics/947e8ed8a8c5.png",
    "subj": "物理"
  },
  "F=kQq/r²": {
    "l": "F = \\frac{kQq}{r^2}",
    "img": "/common/formulas/physics/abbd6efda223.png",
    "subj": "物理"
  },
  "E=F/q": {
    "l": "E = \\frac{F}{q}",
    "img": "/common/formulas/physics/abbd6efda223.png",
    "subj": "物理"
  },
  "E=kQ/r²": {
    "l": "E = \\frac{kQ}{r^2}",
    "img": "/common/formulas/physics/abbd6efda223.png",
    "subj": "物理"
  },
  "E=U/d": {
    "l": "E = \\frac{U}{d}",
    "img": "/common/formulas/physics/abbd6efda223.png",
    "subj": "物理"
  },
  "U=Ed": {
    "l": "U = Ed",
    "img": "/common/formulas/physics/abbd6efda223.png",
    "subj": "物理"
  },
  "C=Q/U": {
    "l": "C = \\frac{Q}{U}",
    "img": "/common/formulas/physics/abbd6efda223.png",
    "subj": "物理"
  },
  "C=εS/(4πkd)": {
    "l": "C = \\frac{\\varepsilon S}{4\\pi k d}",
    "img": "/common/formulas/physics/abbd6efda223.png",
    "subj": "物理"
  },
  "I=Q/t": {
    "l": "I = \\frac{Q}{t}",
    "img": "/common/formulas/physics/d6fe4cb2a612.png",
    "subj": "物理"
  },
  "I=U/R": {
    "l": "I = \\frac{U}{R}",
    "img": "/common/formulas/physics/d6fe4cb2a612.png",
    "subj": "物理"
  },
  "R串=R1+R2": {
    "l": "R_\\text{串} = R_1 + R_2",
    "img": "/common/formulas/physics/d6fe4cb2a612.png",
    "subj": "物理"
  },
  "1/R并=1/R1+1/R2": {
    "l": "\\frac{1}{R_\\text{并}} = \\frac{1}{R_1} + \\frac{1}{R_2}",
    "img": "/common/formulas/physics/d6fe4cb2a612.png",
    "subj": "物理"
  },
  "P=UI=I²R": {
    "l": "P = UI = I^2 R",
    "img": "/common/formulas/physics/d6fe4cb2a612.png",
    "subj": "物理"
  },
  "Q=I²Rt": {
    "l": "Q = I^2 R t",
    "img": "/common/formulas/physics/d6fe4cb2a612.png",
    "subj": "物理"
  },
  "F=BILsinθ": {
    "l": "F = BIL \\sin\\theta",
    "img": "/common/formulas/physics/ae2a280cd431.png",
    "subj": "物理"
  },
  "f=qvBsinθ": {
    "l": "f = qvB \\sin\\theta",
    "img": "/common/formulas/physics/ae2a280cd431.png",
    "subj": "物理"
  },
  "qvB=mv²/r": {
    "l": "qvB = \\frac{m v^2}{r}",
    "img": "/common/formulas/physics/ae2a280cd431.png",
    "subj": "物理"
  },
  "r=mv/(qB)": {
    "l": "r = \\frac{mv}{qB}",
    "img": "/common/formulas/physics/ae2a280cd431.png",
    "subj": "物理"
  },
  "T=2πm/(qB)": {
    "l": "T = \\frac{2\\pi m}{qB}",
    "img": "/common/formulas/physics/ae2a280cd431.png",
    "subj": "物理"
  },
  "Φ=BS": {
    "l": "\\Phi = BS",
    "img": "/common/formulas/physics/506557aed4ca.png",
    "subj": "物理"
  },
  "E=nΔΦ/Δt": {
    "l": "E = n \\frac{\\Delta\\Phi}{\\Delta t}",
    "img": "/common/formulas/physics/506557aed4ca.png",
    "subj": "物理"
  },
  "E=BLvsinθ": {
    "l": "E = BLv \\sin\\theta",
    "img": "/common/formulas/physics/506557aed4ca.png",
    "subj": "物理"
  },
  "E=L·ΔI/Δt": {
    "l": "E = L \\frac{\\Delta I}{\\Delta t}",
    "img": "/common/formulas/physics/506557aed4ca.png",
    "subj": "物理"
  },
  "e=Em sin(ωt)": {
    "l": "e = E_m \\sin(\\omega t)",
    "img": "/common/formulas/physics/614f37e89ce2.png",
    "subj": "物理"
  },
  "Em=nBSω": {
    "l": "E_m = nBS\\omega",
    "img": "/common/formulas/physics/614f37e89ce2.png",
    "subj": "物理"
  },
  "E=Em/√2": {
    "l": "E = \\frac{E_m}{\\sqrt{2}}",
    "img": "/common/formulas/physics/614f37e89ce2.png",
    "subj": "物理"
  },
  "U1/U2=n1/n2": {
    "l": "\\frac{U_1}{U_2} = \\frac{n_1}{n_2}",
    "img": "/common/formulas/physics/614f37e89ce2.png",
    "subj": "物理"
  },
  "P损=(P/U)²R": {
    "l": "P_\\text{损} = \\left(\\frac{P}{U}\\right)^2 R",
    "img": "/common/formulas/physics/614f37e89ce2.png",
    "subj": "物理"
  },
  "F=-kx": {
    "l": "F = -kx",
    "img": "/common/formulas/physics/62d9f35cb9fd.png",
    "subj": "物理"
  },
  "T=2π√(m/k)": {
    "l": "T = 2\\pi \\sqrt{\\frac{m}{k}}",
    "img": "/common/formulas/physics/62d9f35cb9fd.png",
    "subj": "物理"
  },
  "T=2π√(L/g)": {
    "l": "T = 2\\pi \\sqrt{\\frac{L}{g}}",
    "img": "/common/formulas/physics/62d9f35cb9fd.png",
    "subj": "物理"
  },
  "v=λf=λ/T": {
    "l": "v = \\lambda f = \\frac{\\lambda}{T}",
    "img": "/common/formulas/physics/62d9f35cb9fd.png",
    "subj": "物理"
  },
  "n1sini1=n2sini2": {
    "l": "n_1 \\sin i_1 = n_2 \\sin i_2",
    "img": "/common/formulas/physics/07203be1c246.png",
    "subj": "物理"
  },
  "n=c/v": {
    "l": "n = \\frac{c}{v}",
    "img": "/common/formulas/physics/07203be1c246.png",
    "subj": "物理"
  },
  "sinC=1/n": {
    "l": "\\sin C = \\frac{1}{n}",
    "img": "/common/formulas/physics/07203be1c246.png",
    "subj": "物理"
  },
  "Δx=Lλ/d": {
    "l": "\\Delta x = \\frac{L\\lambda}{d}",
    "img": "/common/formulas/physics/07203be1c246.png",
    "subj": "物理"
  },
  "pV/T=C": {
    "l": "\\frac{pV}{T} = C",
    "img": "/common/formulas/physics/0fd91c82e202.png",
    "subj": "物理"
  },
  "p1V1/T1=p2V2/T2": {
    "l": "\\frac{p_1 V_1}{T_1} = \\frac{p_2 V_2}{T_2}",
    "img": "/common/formulas/physics/0fd91c82e202.png",
    "subj": "物理"
  },
  "ΔU=W+Q": {
    "l": "\\Delta U = W + Q",
    "img": "/common/formulas/physics/0fd91c82e202.png",
    "subj": "物理"
  },
  "En=-13.6/n² eV": {
    "l": "E_n = -\\frac{13.6}{n^2} \\text{ eV}",
    "img": "/common/formulas/physics/7397ba554e68.png",
    "subj": "物理"
  },
  "ΔE=hf": {
    "l": "\\Delta E = hf",
    "img": "/common/formulas/physics/7397ba554e68.png",
    "subj": "物理"
  },
  "Ek=hν-W0": {
    "l": "E_k = h\\nu - W_0",
    "img": "/common/formulas/physics/7397ba554e68.png",
    "subj": "物理"
  },
  "ΔE=Δmc²": {
    "l": "\\Delta E = \\Delta m c^2",
    "img": "/common/formulas/physics/7397ba554e68.png",
    "subj": "物理"
  },
  "N=N0·(½)^(t/T)": {
    "l": "N = N_0 \\cdot \\left(\\frac{1}{2}\\right)^{t/T}",
    "img": "/common/formulas/physics/7397ba554e68.png",
    "subj": "物理"
  },
  "n=m/M": {
    "l": "n = \\frac{m}{M}",
    "img": "/common/formulas/chemistry/886a3c801988.png",
    "subj": "化学"
  },
  "N=n·NA": {
    "l": "N = n \\cdot N_A",
    "img": "/common/formulas/chemistry/886a3c801988.png",
    "subj": "化学"
  },
  "c=n/V": {
    "l": "c = \\frac{n}{V}",
    "img": "/common/formulas/chemistry/886a3c801988.png",
    "subj": "化学"
  },
  "Vm=V/n=22.4L/mol(标况)": {
    "l": "V_m = \\frac{V}{n} = 22.4 \\text{ L/mol}\\ \\text{(标况)}",
    "img": "/common/formulas/chemistry/886a3c801988.png",
    "subj": "化学"
  },
  "c浓·V浓=c稀·V稀": {
    "l": "c_\\text{浓} \\cdot V_\\text{浓} = c_\\text{稀} \\cdot V_\\text{稀}",
    "img": "/common/formulas/chemistry/886a3c801988.png",
    "subj": "化学"
  },
  "n(Ox)×|Δv(Ox)| = n(Red)×|Δv(Red)|": {
    "l": "n(\\text{Ox}) \\times |\\Delta v(\\text{Ox})| = n(\\text{Red}) \\times |\\Delta v(\\text{Red})|",
    "img": "/common/formulas/chemistry/57fbcc1a8d78.png",
    "subj": "化学"
  },
  "v=Δc/Δt": {
    "l": "v = \\frac{\\Delta c}{\\Delta t}",
    "img": "/common/formulas/chemistry/a86455779f5c.png",
    "subj": "化学"
  },
  "K=[C]^c[D]^d/([A]^a[B]^b)": {
    "l": "K = \\frac{[\\text{C}]^c [\\text{D}]^d}{[\\text{A}]^a [\\text{B}]^b}",
    "img": "/common/formulas/chemistry/a86455779f5c.png",
    "subj": "化学"
  },
  "α=已转化/起始×100%": {
    "l": "\\alpha = \\frac{\\text{已转化}}{\\text{起始}} \\times 100\\%",
    "img": "/common/formulas/chemistry/a86455779f5c.png",
    "subj": "化学"
  },
  "E池=E正-E负": {
    "l": "E_\\text{池} = E_\\text{正} - E_\\text{负}",
    "img": "/common/formulas/chemistry/71b7e41ec667.png",
    "subj": "化学"
  },
  "Q=It=nF": {
    "l": "Q = It = nF",
    "img": "/common/formulas/chemistry/71b7e41ec667.png",
    "subj": "化学"
  },
  "m=M·Q/(nF)": {
    "l": "m = \\frac{M \\cdot Q}{nF}",
    "img": "/common/formulas/chemistry/71b7e41ec667.png",
    "subj": "化学"
  },
  "Kw=c(H⁺)·c(OH⁻)=10⁻¹⁴": {
    "l": "K_w = c(\\text{H}^+) \\cdot c(\\text{OH}^-) = 10^{-14}",
    "img": "/common/formulas/chemistry/e31151fdb350.png",
    "subj": "化学"
  },
  "pH=-lg[c(H⁺)]": {
    "l": "pH = -\\lg[c(\\text{H}^+)]",
    "img": "/common/formulas/chemistry/e31151fdb350.png",
    "subj": "化学"
  },
  "Ksp=[A⁺][B⁻]": {
    "l": "K_{sp} = [\\text{A}^+][\\text{B}^-]",
    "img": "/common/formulas/chemistry/e31151fdb350.png",
    "subj": "化学"
  },
  "pH=pKa+lg([A⁻]/[HA])": {
    "l": "pH = pK_a + \\lg\\frac{[\\text{A}^-]}{[\\text{HA}]}",
    "img": "/common/formulas/chemistry/e31151fdb350.png",
    "subj": "化学"
  },
  "ΔH=ΣE(反应物)-ΣE(生成物)": {
    "l": "\\Delta H = \\sum E(\\text{反应物}) - \\sum E(\\text{生成物})",
    "img": "/common/formulas/chemistry/c730a232abd4.png",
    "subj": "化学"
  },
  "ΔG=ΔH-TΔS": {
    "l": "\\Delta G = \\Delta H - T\\Delta S",
    "img": "/common/formulas/chemistry/c730a232abd4.png",
    "subj": "化学"
  },
  "ΔG<0自发": {
    "l": "\\Delta G < 0 \\quad \\text{自发}",
    "img": "/common/formulas/chemistry/c730a232abd4.png",
    "subj": "化学"
  },
  "ATP → ADP + Pi + 能量": {
    "l": "ATP \\to ADP + P_i + \\text{能量}",
    "img": "/common/formulas/biology/6a05012f7489.png",
    "subj": "生物"
  },
  "ADP + Pi + 能量 → ATP": {
    "l": "ADP + P_i + \\text{能量} \\to ATP",
    "img": "/common/formulas/biology/6a05012f7489.png",
    "subj": "生物"
  },
  "CO2 + C5 → 2C3": {
    "l": "CO_2 + C_5 \\to 2C_3",
    "img": "/common/formulas/biology/a25e404f2c7f.png",
    "subj": "生物"
  },
  "2C3 + [H] + ATP → (CH2O) + C5": {
    "l": "2C_3 + [\\text{H}] + ATP \\to (CH_2O) + C_5",
    "img": "/common/formulas/biology/a25e404f2c7f.png",
    "subj": "生物"
  },
  "6CO2 + 12H2O → C6H12O6 + 6O2 + 6H2O": {
    "l": "6CO_2 + 12H_2O \\to C_6H_{12}O_6 + 6O_2 + 6H_2O",
    "img": "/common/formulas/biology/a25e404f2c7f.png",
    "subj": "生物"
  },
  "C6H12O6+6O2→6CO2+6H2O+2870kJ": {
    "l": "C_6H_{12}O_6 + 6O_2 \\to 6CO_2 + 6H_2O + 2870 \\text{ kJ}",
    "img": "/common/formulas/biology/50448e74e0ea.png",
    "subj": "生物"
  },
  "C6H12O6→2C3H6O3(乳酸)+少量ATP": {
    "l": "C_6H_{12}O_6 \\to 2C_3H_6O_3\\ \\text{(乳酸)} + \\text{少量} ATP",
    "img": "/common/formulas/biology/50448e74e0ea.png",
    "subj": "生物"
  },
  "C6H12O6→2C2H5OH+2CO2+少量ATP": {
    "l": "C_6H_{12}O_6 \\to 2C_2H_5OH + 2CO_2 + \\text{少量} ATP",
    "img": "/common/formulas/biology/50448e74e0ea.png",
    "subj": "生物"
  },
  "A-T, G-C": {
    "l": "A\\text{-}T,\\ G\\text{-}C",
    "img": "/common/formulas/biology/faa63519970c.png",
    "subj": "生物"
  },
  "A-U, G-C": {
    "l": "A\\text{-}U,\\ G\\text{-}C",
    "img": "/common/formulas/biology/faa63519970c.png",
    "subj": "生物"
  },
  "1密码子=3碱基=1氨基酸": {
    "l": "1 \\text{密码子} = 3 \\text{碱基} = 1 \\text{氨基酸}",
    "img": "/common/formulas/biology/faa63519970c.png",
    "subj": "生物"
  },
  "64密码子=61编码+3终止": {
    "l": "64 \\text{密码子} = 61 \\text{编码} + 3 \\text{终止}",
    "img": "/common/formulas/biology/faa63519970c.png",
    "subj": "生物"
  },
  "Aa × Aa → 1AA:2Aa:1aa": {
    "l": "Aa \\times Aa \\to 1AA : 2Aa : 1aa",
    "img": "/common/formulas/biology/b34848d83760.png",
    "subj": "生物"
  },
  "3:1(完全显性)": {
    "l": "3 : 1 \\quad \\text{(完全显性)}",
    "img": "/common/formulas/biology/b34848d83760.png",
    "subj": "生物"
  },
  "1:2:1(基因型)": {
    "l": "1 : 2 : 1 \\quad \\text{(基因型)}",
    "img": "/common/formulas/biology/b34848d83760.png",
    "subj": "生物"
  },
  "AaBb × AaBb → 9:3:3:1": {
    "l": "AaBb \\times AaBb \\to 9 : 3 : 3 : 1",
    "img": "/common/formulas/biology/b34848d83760.png",
    "subj": "生物"
  },
  "N=M×n/m": {
    "l": "N = \\frac{M \\times n}{m}",
    "img": "/common/formulas/biology/203ef8243ea2.png",
    "subj": "生物"
  },
  "传递效率=下一营养级同化量/上一营养级同化量×100%": {
    "l": "\\text{传递效率} = \\frac{\\text{下一营养级同化量}}{\\text{上一营养级同化量}} \\times 100\\%",
    "img": "/common/formulas/biology/ec1ed8d21280.png",
    "subj": "生物"
  },
  "10%≤效率≤20%": {
    "l": "10\\% \\le \\text{效率} \\le 20\\%",
    "img": "/common/formulas/biology/ec1ed8d21280.png",
    "subj": "生物"
  },
  "H=90°-|φ-δ|": {
    "l": "H = 90° - |\\varphi - \\delta|",
    "img": "/common/formulas/geography/4058ab6c883d.png",
    "subj": "地理"
  },
  "所求区时=已知区时±时区差": {
    "l": "\\text{所求区时} = \\text{已知区时} \\pm \\text{时区差}",
    "img": "/common/formulas/geography/4058ab6c883d.png",
    "subj": "地理"
  },
  "t = t0 / sqrt(1 - v^2/c^2)": {
    "l": "t = \\frac{t_0}{\\sqrt{1 - v^2/c^2}}",
    "img": "/common/formulas/extra-physics/3dcdcb77182b.png",
    "subj": "拓展物理"
  },
  "L = L0 * sqrt(1 - v^2/c^2)": {
    "l": "L = L_0 \\sqrt{1 - v^2/c^2}",
    "img": "/common/formulas/extra-physics/3dcdcb77182b.png",
    "subj": "拓展物理"
  },
  "p = mv": {
    "l": "p = mv",
    "img": "/common/formulas/extra-physics/d9ac978fc8d7.png",
    "subj": "拓展物理"
  },
  "I = Δp = Ft": {
    "l": "I = \\Delta p = Ft",
    "img": "/common/formulas/extra-physics/d9ac978fc8d7.png",
    "subj": "拓展物理"
  }
}
