/**
 * 闪念小抄 - 公式 Unicode → LaTeX 对照表
 *
 * 键:knowledgeData.js / sample.js 中 formulas 字段的原始 Unicode 文本(逐字符精确空格)。
 * 值:对应的 KaTeX 可渲染 LaTeX 源(反斜杠在 JS 字符串里需 \\ 转义)。
 *
 * 翻译规约:
 *  - 集合:∪→\cup  ∩→\cap  ∈→\in  ⊆→\subseteq  {}→\{\ \}  或/且→\text{或}/\text{且}
 *  - 关系:±→\pm  ≥→\ge  ≤→\le  →→\to  ⇒→\Rightarrow  ∥→\parallel  ≈→\approx
 *  - 字母变体:上标²/³→^2/^3  下标数字→_{1}  v̄(带杠)→\bar{v}
 *  - 根号:√(...)→\sqrt{...}  ³√→\sqrt[3]{...}
 *  - 分式:含 / 的比值优先用 \frac{}{} 变量+字母组合;纯量除法如 v0²/(2g) 用 \frac
 *  - 函数:lg→\lg  log→\log  sin/cos/tan→\sin/\cos/\tan
 *  - 求和:Σ→\sum  连乘 → 用显式
 *  - 排列组合:A_n^k→A_n^k  C_n^k→C_n^k  (直接上下标,无需 binom)
 *  - 中文一律用 \text{...} 包裹,保留全角/半角原样
 *  - 生物化学方程式:箭头用 \to,化学式下标用 _{} (如 CO_2),能量项用 \text{}
 *  - 生物遗传陈述(A-T 等):逐字符忠实表达,中文 \text{} 包裹
 *
 * 范围:数学/物理/化学/生物/地理/拓展物理 共168条唯一。
 * 信息技术(58条Python代码)、英语(4条语法)不渲染,不在本表(content.ux 对它们保留 Unicode text)。
 */

export default {
  // ==================== 数学 (52) ====================
  'A∪B={x|x∈A或x∈B}': 'A \\cup B = \\{x \\mid x \\in A \\text{ 或 } x \\in B\\}',
  'A∩B={x|x∈A且x∈B}': 'A \\cap B = \\{x \\mid x \\in A \\text{ 且 } x \\in B\\}',
  '|A∪B|=|A|+|B|-|A∩B|': '|A \\cup B| = |A| + |B| - |A \\cap B|',
  'f(-x)=-f(x)': 'f(-x) = -f(x)',
  'f(-x)=f(x)': 'f(-x) = f(x)',
  'f(x+T)=f(x)': 'f(x+T) = f(x)',
  'y=f(x+a)': 'y = f(x+a)',
  'a^m·a^n=a^(m+n)': 'a^m \\cdot a^n = a^{m+n}',
  'log_a(MN)=log_a M+log_a N': '\\log_a (MN) = \\log_a M + \\log_a N',
  'log_a a^x=x': '\\log_a a^x = x',
  'a^(log_a N)=N': 'a^{\\log_a N} = N',
  'x=-b/(2a)': 'x = -\\frac{b}{2a}',
  'Δ=b²-4ac': '\\Delta = b^2 - 4ac',
  'x1+x2=-b/a': 'x_1 + x_2 = -\\frac{b}{a}',
  'x1·x2=c/a': 'x_1 \\cdot x_2 = \\frac{c}{a}',
  "(x^n)'=nx^(n-1)": '(x^n)\' = n x^{n-1}',
  "(sin x)'=cos x": '(\sin x)\' = \cos x',
  "(cos x)'=-sin x": '(\cos x)\' = -\sin x',
  "(e^x)'=e^x": '(e^x)\' = e^x',
  "(ln x)'=1/x": '(\\ln x)\' = \\frac{1}{x}',
  "(uv)'=u'v+uv'": "(uv)' = u'v + uv'",
  'sin²+cos²=1': '\\sin^2 x + \\cos^2 x = 1',
  'sin(A±B)=sinAcosB±cosAsinB': '\\sin(A \\pm B) = \\sin A \\cos B \\pm \\cos A \\sin B',
  'cos2α=2cos²α-1': '\\cos 2\\alpha = 2\\cos^2 \\alpha - 1',
  'sin2α=2sinαcosα': '\\sin 2\\alpha = 2 \\sin \\alpha \\cos \\alpha',
  'y=Asin(ωx+φ)': 'y = A \\sin(\\omega x + \\varphi)',
  'T=2π/ω': 'T = \\frac{2\\pi}{\\omega}',
  'a·b=|a||b|cosθ': '\\vec{a} \\cdot \\vec{b} = |\\vec{a}||\\vec{b}|\\cos\\theta',
  'a·b=x1x2+y1y2': '\\vec{a} \\cdot \\vec{b} = x_1 x_2 + y_1 y_2',
  '|a|=√(x²+y²)': '|\\vec{a}| = \\sqrt{x^2 + y^2}',
  'a∥b⇒x1y2=x2y1': '\\vec{a} \\parallel \\vec{b} \\Rightarrow x_1 y_2 = x_2 y_1',
  'an=a1+(n-1)d': 'a_n = a_1 + (n-1)d',
  'Sn=n(a1+an)/2': 'S_n = \\frac{n(a_1 + a_n)}{2}',
  'an=a1·q^(n-1)': 'a_n = a_1 \\cdot q^{n-1}',
  'Sn=a1(1-q^n)/(1-q)': 'S_n = \\frac{a_1(1 - q^n)}{1 - q}',
  'a+b≥2√(ab)': 'a + b \\ge 2\\sqrt{ab}',
  '(a+b+c)/3≥³√(abc)': '\\frac{a+b+c}{3} \\ge \\sqrt[3]{abc}',
  '(Σa_i²)(Σb_i²)≥(Σa_ib_i)²': '(\\sum a_i^2)(\\sum b_i^2) \\ge (\\sum a_i b_i)^2',
  'd=|n·PA|/|n|': 'd = \\frac{|\\vec{n} \\cdot \\vec{PA}|}{|\\vec{n}|}',
  'V=1/3·Sh': 'V = \\frac{1}{3} S h',
  'cosθ=|n1·n2|/(|n1||n2|)': '\\cos\\theta = \\frac{|\\vec{n_1} \\cdot \\vec{n_2}|}{|\\vec{n_1}||\\vec{n_2}|}',
  'd=|Ax0+By0+C|/√(A²+B²)': 'd = \\frac{|Ax_0 + By_0 + C|}{\\sqrt{A^2 + B^2}}',
  'x²/a²+y²/b²=1': '\\frac{x^2}{a^2} + \\frac{y^2}{b^2} = 1',
  'x²/a²-y²/b²=1': '\\frac{x^2}{a^2} - \\frac{y^2}{b^2} = 1',
  'y²=2px': 'y^2 = 2px',
  'c²=a²-b²(椭圆)': 'c^2 = a^2 - b^2 \\quad \\text{(椭圆)}',
  'c²=a²+b²(双曲线)': 'c^2 = a^2 + b^2 \\quad \\text{(双曲线)}',
  'A_n^k=n!/(n-k)!': 'A_n^k = \\frac{n!}{(n-k)!}',
  'C_n^k=n!/[k!(n-k)!]': 'C_n^k = \\frac{n!}{k!(n-k)!}',
  'P(X=k)=C_n^k·p^k·(1-p)^(n-k)': 'P(X=k) = C_n^k \\cdot p^k \\cdot (1-p)^{n-k}',
  'E(X)=np': 'E(X) = np',
  'D(X)=np(1-p)': 'D(X) = np(1-p)',

  // ==================== 物理 (72) ====================
  'v=v0+at': 'v = v_0 + at',
  'x=v0t+½at²': 'x = v_0 t + \\frac{1}{2} a t^2',
  'v²-v0²=2ax': 'v^2 - v_0^2 = 2ax',
  'v̄=(v0+v)/2': '\\bar{v} = \\frac{v_0 + v}{2}',
  'h=½gt²': 'h = \\frac{1}{2} g t^2',
  'H=v0²/(2g)': 'H = \\frac{v_0^2}{2g}',
  'G=mg': 'G = mg',
  'F=kx': 'F = kx',
  'f=μN': 'f = \\mu N',
  'F=√(Fx²+Fy²)': 'F = \\sqrt{F_x^2 + F_y^2}',
  'F合=ma': 'F_\\text{合} = ma',
  'N=mg+ma(超重)': 'N = mg + ma \\quad \\text{(超重)}',
  'N=mg-ma(失重)': 'N = mg - ma \\quad \\text{(失重)}',
  'x=v0t': 'x = v_0 t',
  'y=½gt²': 'y = \\frac{1}{2} g t^2',
  'F向=mv²/r': 'F_\\text{向} = \\frac{m v^2}{r}',
  'F=Gm1m2/r²': 'F = \\frac{G m_1 m_2}{r^2}',
  'v=√(GM/r)': 'v = \\sqrt{\\frac{GM}{r}}',
  'T=2π√(r³/GM)': 'T = 2\\pi \\sqrt{\\frac{r^3}{GM}}',
  'W=Fscosθ': 'W = Fs \\cos\\theta',
  'P=Fv': 'P = Fv',
  'Ek=½mv²': 'E_k = \\frac{1}{2} m v^2',
  'Ep=mgh': 'E_p = mgh',
  'Ep=½kx²': 'E_p = \\frac{1}{2} k x^2',
  'W合=ΔEk': 'W_\\text{合} = \\Delta E_k',
  'p=mv': 'p = mv',
  'F·t=Δp': 'F \\cdot t = \\Delta p',
  "m1v1+m2v2=m1v1'+m2v2'": "m_1 v_1 + m_2 v_2 = m_1 v_1' + m_2 v_2'",
  'v共=(m1v1+m2v2)/(m1+m2)': 'v_\\text{共} = \\frac{m_1 v_1 + m_2 v_2}{m_1 + m_2}',
  'F=kQq/r²': 'F = \\frac{kQq}{r^2}',
  'E=F/q': 'E = \\frac{F}{q}',
  'E=kQ/r²': 'E = \\frac{kQ}{r^2}',
  'E=U/d': 'E = \\frac{U}{d}',
  'U=Ed': 'U = Ed',
  'C=Q/U': 'C = \\frac{Q}{U}',
  'C=εS/(4πkd)': 'C = \\frac{\\varepsilon S}{4\\pi k d}',
  'I=Q/t': 'I = \\frac{Q}{t}',
  'I=U/R': 'I = \\frac{U}{R}',
  'R串=R1+R2': 'R_\\text{串} = R_1 + R_2',
  '1/R并=1/R1+1/R2': '\\frac{1}{R_\\text{并}} = \\frac{1}{R_1} + \\frac{1}{R_2}',
  'P=UI=I²R': 'P = UI = I^2 R',
  'Q=I²Rt': 'Q = I^2 R t',
  'F=BILsinθ': 'F = BIL \\sin\\theta',
  'f=qvBsinθ': 'f = qvB \\sin\\theta',
  'qvB=mv²/r': 'qvB = \\frac{m v^2}{r}',
  'r=mv/(qB)': 'r = \\frac{mv}{qB}',
  'T=2πm/(qB)': 'T = \\frac{2\\pi m}{qB}',
  'Φ=BS': '\\Phi = BS',
  'E=nΔΦ/Δt': 'E = n \\frac{\\Delta\\Phi}{\\Delta t}',
  'E=BLvsinθ': 'E = BLv \\sin\\theta',
  'E=L·ΔI/Δt': 'E = L \\frac{\\Delta I}{\\Delta t}',
  'e=Em sin(ωt)': 'e = E_m \\sin(\\omega t)',
  'Em=nBSω': 'E_m = nBS\\omega',
  'E=Em/√2': 'E = \\frac{E_m}{\\sqrt{2}}',
  'U1/U2=n1/n2': '\\frac{U_1}{U_2} = \\frac{n_1}{n_2}',
  'P损=(P/U)²R': 'P_\\text{损} = \\left(\\frac{P}{U}\\right)^2 R',
  'F=-kx': 'F = -kx',
  'T=2π√(m/k)': 'T = 2\\pi \\sqrt{\\frac{m}{k}}',
  'T=2π√(L/g)': 'T = 2\\pi \\sqrt{\\frac{L}{g}}',
  'v=λf=λ/T': 'v = \\lambda f = \\frac{\\lambda}{T}',
  'n1sini1=n2sini2': 'n_1 \\sin i_1 = n_2 \\sin i_2',
  'n=c/v': 'n = \\frac{c}{v}',
  'sinC=1/n': '\\sin C = \\frac{1}{n}',
  'Δx=Lλ/d': '\\Delta x = \\frac{L\\lambda}{d}',
  'pV/T=C': '\\frac{pV}{T} = C',
  'p1V1/T1=p2V2/T2': '\\frac{p_1 V_1}{T_1} = \\frac{p_2 V_2}{T_2}',
  'ΔU=W+Q': '\\Delta U = W + Q',
  'En=-13.6/n² eV': 'E_n = -\\frac{13.6}{n^2} \\text{ eV}',
  'ΔE=hf': '\\Delta E = hf',
  'Ek=hν-W0': 'E_k = h\\nu - W_0',
  'ΔE=Δmc²': '\\Delta E = \\Delta m c^2',
  'N=N0·(½)^(t/T)': 'N = N_0 \\cdot \\left(\\frac{1}{2}\\right)^{t/T}',

  // ==================== 化学 (19) ====================
  'n=m/M': 'n = \\frac{m}{M}',
  'N=n·NA': 'N = n \\cdot N_A',
  'c=n/V': 'c = \\frac{n}{V}',
  'Vm=V/n=22.4L/mol(标况)': 'V_m = \\frac{V}{n} = 22.4 \\text{ L/mol}\\ \\text{(标况)}',
  'c浓·V浓=c稀·V稀': 'c_\\text{浓} \\cdot V_\\text{浓} = c_\\text{稀} \\cdot V_\\text{稀}',
  'n(Ox)×|Δv(Ox)| = n(Red)×|Δv(Red)|': 'n(\\text{Ox}) \\times |\\Delta v(\\text{Ox})| = n(\\text{Red}) \\times |\\Delta v(\\text{Red})|',
  'v=Δc/Δt': 'v = \\frac{\\Delta c}{\\Delta t}',
  'K=[C]^c[D]^d/([A]^a[B]^b)': 'K = \\frac{[\\text{C}]^c [\\text{D}]^d}{[\\text{A}]^a [\\text{B}]^b}',
  'α=已转化/起始×100%': '\\alpha = \\frac{\\text{已转化}}{\\text{起始}} \\times 100\\%',
  'E池=E正-E负': 'E_\\text{池} = E_\\text{正} - E_\\text{负}',
  'Q=It=nF': 'Q = It = nF',
  'm=M·Q/(nF)': 'm = \\frac{M \\cdot Q}{nF}',
  'Kw=c(H⁺)·c(OH⁻)=10⁻¹⁴': 'K_w = c(\\text{H}^+) \\cdot c(\\text{OH}^-) = 10^{-14}',
  'pH=-lg[c(H⁺)]': 'pH = -\\lg[c(\\text{H}^+)]',
  'Ksp=[A⁺][B⁻]': 'K_{sp} = [\\text{A}^+][\\text{B}^-]',
  'pH=pKa+lg([A⁻]/[HA])': 'pH = pK_a + \\lg\\frac{[\\text{A}^-]}{[\\text{HA}]}',
  'ΔH=ΣE(反应物)-ΣE(生成物)': '\\Delta H = \\sum E(\\text{反应物}) - \\sum E(\\text{生成物})',
  'ΔG=ΔH-TΔS': '\\Delta G = \\Delta H - T\\Delta S',
  'ΔG<0自发': '\\Delta G < 0 \\quad \\text{自发}',

  // ==================== 生物 (19) — 化学方程式 + 遗传陈述 ====================
  'ATP → ADP + Pi + 能量': 'ATP \\to ADP + P_i + \\text{能量}',
  'ADP + Pi + 能量 → ATP': 'ADP + P_i + \\text{能量} \\to ATP',
  'CO2 + C5 → 2C3': 'CO_2 + C_5 \\to 2C_3',
  '2C3 + [H] + ATP → (CH2O) + C5': '2C_3 + [\\text{H}] + ATP \\to (CH_2O) + C_5',
  '6CO2 + 12H2O → C6H12O6 + 6O2 + 6H2O': '6CO_2 + 12H_2O \\to C_6H_{12}O_6 + 6O_2 + 6H_2O',
  'C6H12O6+6O2→6CO2+6H2O+2870kJ': 'C_6H_{12}O_6 + 6O_2 \\to 6CO_2 + 6H_2O + 2870 \\text{ kJ}',
  'C6H12O6→2C3H6O3(乳酸)+少量ATP': 'C_6H_{12}O_6 \\to 2C_3H_6O_3\\ \\text{(乳酸)} + \\text{少量} ATP',
  'C6H12O6→2C2H5OH+2CO2+少量ATP': 'C_6H_{12}O_6 \\to 2C_2H_5OH + 2CO_2 + \\text{少量} ATP',
  'A-T, G-C': 'A\\text{-}T,\\ G\\text{-}C',
  'A-U, G-C': 'A\\text{-}U,\\ G\\text{-}C',
  '1密码子=3碱基=1氨基酸': '1 \\text{密码子} = 3 \\text{碱基} = 1 \\text{氨基酸}',
  '64密码子=61编码+3终止': '64 \\text{密码子} = 61 \\text{编码} + 3 \\text{终止}',
  'Aa × Aa → 1AA:2Aa:1aa': 'Aa \\times Aa \\to 1AA : 2Aa : 1aa',
  '3:1(完全显性)': '3 : 1 \\quad \\text{(完全显性)}',
  '1:2:1(基因型)': '1 : 2 : 1 \\quad \\text{(基因型)}',
  'AaBb × AaBb → 9:3:3:1': 'AaBb \\times AaBb \\to 9 : 3 : 3 : 1',
  'N=M×n/m': 'N = \\frac{M \\times n}{m}',
  '传递效率=下一营养级同化量/上一营养级同化量×100%': '\\text{传递效率} = \\frac{\\text{下一营养级同化量}}{\\text{上一营养级同化量}} \\times 100\\%',
  '10%≤效率≤20%': '10\\% \\le \\text{效率} \\le 20\\%',

  // ==================== 地理 (2) ====================
  'H=90°-|φ-δ|': 'H = 90° - |\\varphi - \\delta|',
  '所求区时=已知区时±时区差': '\\text{所求区时} = \\text{已知区时} \\pm \\text{时区差}',

  // ==================== 拓展物理 (4) — 来自 extras/sample.js ====================
  't = t0 / sqrt(1 - v^2/c^2)': 't = \\frac{t_0}{\\sqrt{1 - v^2/c^2}}',
  'L = L0 * sqrt(1 - v^2/c^2)': 'L = L_0 \\sqrt{1 - v^2/c^2}',
  'p = mv': 'p = mv',
  'I = Δp = Ft': 'I = \\Delta p = Ft'
}
