/* AUTO-GENERATED by scripts/gen_formulas.js — 勿手改 */
export default {
  "数学#1": {
    "img": "/common/formulas/math/46c4c6a9af0a.png",
    "w": 336,
    "h": 241
  },
  "数学#2": {
    "img": "/common/formulas/math/8a76e3c75906.png",
    "w": 336,
    "h": 321
  },
  "数学#3": {
    "img": "/common/formulas/math/fe17ec2e45a2.png",
    "w": 336,
    "h": 322
  },
  "数学#4": {
    "img": "/common/formulas/math/00c2b1a50254.png",
    "w": 336,
    "h": 363
  },
  "数学#5": {
    "img": "/common/formulas/math/86d29542d3f1.png",
    "w": 336,
    "h": 496
  },
  "数学#6": {
    "img": "/common/formulas/math/9bed8994d2d1.png",
    "w": 370,
    "h": 496
  },
  "数学#7": {
    "img": "/common/formulas/math/3e6575ab871d.png",
    "w": 336,
    "h": 329
  },
  "数学#8": {
    "img": "/common/formulas/math/ac42e132669e.png",
    "w": 336,
    "h": 358
  },
  "数学#9": {
    "img": "/common/formulas/math/612cb1f5260a.png",
    "w": 336,
    "h": 266
  },
  "数学#10": {
    "img": "/common/formulas/math/44ebeb3acafb.png",
    "w": 336,
    "h": 303
  },
  "数学#11": {
    "img": "/common/formulas/math/c592910d413a.png",
    "w": 336,
    "h": 539
  },
  "数学#12": {
    "img": "/common/formulas/math/0df42dc3e201.png",
    "w": 336,
    "h": 443
  },
  "物理#1": {
    "img": "/common/formulas/physics/ed3b561128a8.png",
    "w": 336,
    "h": 546
  },
  "物理#2": {
    "img": "/common/formulas/physics/1d514924e264.png",
    "w": 336,
    "h": 333
  },
  "物理#3": {
    "img": "/common/formulas/physics/8398c3204a9b.png",
    "w": 336,
    "h": 241
  },
  "物理#4": {
    "img": "/common/formulas/physics/9acae4baba40.png",
    "w": 336,
    "h": 576
  },
  "物理#5": {
    "img": "/common/formulas/physics/cba3fb462738.png",
    "w": 336,
    "h": 511
  },
  "物理#6": {
    "img": "/common/formulas/physics/947e8ed8a8c5.png",
    "w": 336,
    "h": 338
  },
  "物理#7": {
    "img": "/common/formulas/physics/abbd6efda223.png",
    "w": 336,
    "h": 659
  },
  "物理#8": {
    "img": "/common/formulas/physics/d6fe4cb2a612.png",
    "w": 336,
    "h": 530
  },
  "物理#9": {
    "img": "/common/formulas/physics/ae2a280cd431.png",
    "w": 336,
    "h": 452
  },
  "物理#10": {
    "img": "/common/formulas/physics/506557aed4ca.png",
    "w": 336,
    "h": 352
  },
  "物理#11": {
    "img": "/common/formulas/physics/614f37e89ce2.png",
    "w": 336,
    "h": 561
  },
  "物理#12": {
    "img": "/common/formulas/physics/62d9f35cb9fd.png",
    "w": 336,
    "h": 395
  },
  "物理#13": {
    "img": "/common/formulas/physics/07203be1c246.png",
    "w": 336,
    "h": 362
  },
  "物理#14": {
    "img": "/common/formulas/physics/0fd91c82e202.png",
    "w": 336,
    "h": 275
  },
  "物理#15": {
    "img": "/common/formulas/physics/7397ba554e68.png",
    "w": 336,
    "h": 444
  },
  "化学#1": {
    "img": "/common/formulas/chemistry/886a3c801988.png",
    "w": 336,
    "h": 438
  },
  "化学#2": {
    "img": "/common/formulas/chemistry/57fbcc1a8d78.png",
    "w": 397,
    "h": 81
  },
  "化学#4": {
    "img": "/common/formulas/chemistry/a86455779f5c.png",
    "w": 336,
    "h": 295
  },
  "化学#5": {
    "img": "/common/formulas/chemistry/71b7e41ec667.png",
    "w": 336,
    "h": 257
  },
  "化学#6": {
    "img": "/common/formulas/chemistry/e31151fdb350.png",
    "w": 336,
    "h": 345
  },
  "化学#10": {
    "img": "/common/formulas/chemistry/c730a232abd4.png",
    "w": 371,
    "h": 248
  },
  "生物#3": {
    "img": "/common/formulas/biology/6a05012f7489.png",
    "w": 336,
    "h": 161
  },
  "生物#4": {
    "img": "/common/formulas/biology/a25e404f2c7f.png",
    "w": 411,
    "h": 241
  },
  "生物#5": {
    "img": "/common/formulas/biology/50448e74e0ea.png",
    "w": 419,
    "h": 241
  },
  "生物#7": {
    "img": "/common/formulas/biology/faa63519970c.png",
    "w": 336,
    "h": 319
  },
  "生物#8": {
    "img": "/common/formulas/biology/b34848d83760.png",
    "w": 336,
    "h": 319
  },
  "生物#10": {
    "img": "/common/formulas/biology/203ef8243ea2.png",
    "w": 336,
    "h": 96
  },
  "生物#11": {
    "img": "/common/formulas/biology/ec1ed8d21280.png",
    "w": 380,
    "h": 175
  },
  "地理#1": {
    "img": "/common/formulas/geography/4058ab6c883d.png",
    "w": 336,
    "h": 160
  },
  "拓展物理#1": {
    "img": "/common/formulas/extra-physics/3dcdcb77182b.png",
    "w": 336,
    "h": 186
  },
  "拓展物理#2": {
    "img": "/common/formulas/extra-physics/d9ac978fc8d7.png",
    "w": 336,
    "h": 161
  }
}
